
services:

  incodetrade_db:
    image: postgres:17.10
    container_name: incodetrade_db
    ports:
      - "5432:5432"
    restart: no
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: incodetrade_db
    volumes:
      - incodetrade_db_data:/var/lib/postgresql/data
    networks:
      - incodetrade_network

volumes:
  incodetrade_db_data:

networks:
  incodetrade_network:
    driver: bridge
